### ISSUE TITLE
Compatibility with graalpy on MacOSX

### ISSUE THREAD

**Issue by LRGH** [lief-project/LIEF#1032]
**Describe the bug**
`pip install lief` fails when running on github hosted macos with graalpy.

**To Reproduce**
Create a github action with:
```
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-11", "macos-12", "macos-13"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "graalpy-22.3"
    - name: Get and install LIEF
      run: |
        pip install lief
```

**Expected behavior**
Should be sucessful, as it it the case with the same graalpy version and ubuntu, or with the same OS but other python variants (e.g. 3.10 or pypy3.9)

**Environment (please complete the following information):**
 - System and Version : MacOS 10, 11, 12
 - Target format : all
 - LIEF commit version: the one from pip install

**Additional context**

**NOTICE**

If the issue does not contain enough information to be reproduced,
it will be flagged as [incomplete](https://github.com/lief-project/LIEF/issues?q=is%3Aissue+is%3Aclosed+label%3AIncomplete)
and closed.

**/NOTICE**
